### Автор ноутбука -- Булат Ибрагимов (github.com/ibr11)

## Занятие 1. Библиотека Numpy. 

#### При подготовке ноутбука использовался сайт: http://www.inp.nsk.su/~grozin/python/

<img align=center src="http://www.wizdomhub.com/wp-content/uploads/2017/08/numpy_project_page.jpg" style="height:160px;" />

---

Пакет `numpy`(НамПай) предоставляет $n$-мерные однородные массивы (все элементы одного типа); в них нельзя вставить или удалить элемент в произвольном месте. В `numpy` реализовано много операций над массивами в целом. Если задачу можно решить, произведя некоторую последовательность операций над массивами, то это будет столь же эффективно, как в `C` или `matlab` - львиная доля времени тратится в библиотечных функциях, написанных на `C`.

## Одномерные массивы

In [2]:
import numpy as np

Можно преобразовать список в массив.

In [3]:
a = np.array([3, 4, 1])
a, type(a)

(array([3, 4, 1]), numpy.ndarray)

`print` печатает массивы в удобной форме.

In [ ]:
print(a)

Класс `ndarray` имеет много методов.

In [ ]:
set(dir(a)) - set(dir(object))

Наш массив одномерный.

In [ ]:
a.ndim

In [ ]:
print(a)

В $n$-мерном случае возвращается кортеж размеров по каждой координате.

ndarray.ndim — число осей (измерений) массива. Как уже было сказано, в мире Python число измерений часто называют рангом.

ndarray.shape — размеры массива, его форма. Это кортеж натуральных чисел, показывающий длину массива по каждой оси. Для матрицы из n строк и m столбов, shape будет (n,m). 



In [ ]:
a.shape

In [ ]:
len(a), a.size

#### Вопрос
Как связаны элементы кортежа shape, ndim, size?

`numpy` предоставляет несколько типов для целых (`int16`, `int32`, `int64`) и чисел с плавающей точкой (`float32`, `float64`).

In [ ]:
a.dtype, a.dtype.name, a.itemsize

Массивы - изменяемые объекты, в отличие от кортежей

In [ ]:
a[1] = 3
print(a)

Массивы, разумеется, можно использовать в `for` циклах. Но при этом теряется главное преимущество `numpy` - быстродействие. Всегда, когда это возможно, лучше использовать операции над массивами как едиными целыми.

In [ ]:
%%time
for i in a:
    print(i)

In [ ]:
%%time
print(a)

Массив чисел с плавающей точкой.

In [ ]:
b = np.array([0., 2, 1])
b.dtype

Точно такой же массив.

In [6]:
c = np.array([0, 2, 1], dtype=np.float64)
print(c)


[0. 2. 1.]


Преобразование данных

In [7]:
print(c.dtype)
print(c.astype(int))
print(c.astype(str))

float64
[0 2 1]
['0.0' '2.0' '1.0']


Массив, значения которого вычисляются функцией. Функции передаётся массив. Так что в ней можно использовать только такие операции, которые применимы к массивам.

In [5]:
def f(i):
    print(i)
    return i ** 2

a = np.fromfunction(f, (5,), dtype=np.int64)
print(a)

[0 1 2 3 4]
[ 0  1  4  9 16]


In [9]:
a = np.fromfunction(f, (5,), dtype=np.float64)
print(a)

[0. 1. 2. 3. 4.]
[ 0.  1.  4.  9. 16.]


Массивы, заполненные нулями или единицами. Часто лучше сначала создать такой массив, а потом присваивать значения его элементам.

In [10]:
a = np.zeros(3)
print(a)

[0. 0. 0.]


In [11]:
b = np.ones(3, dtype=np.int64)
print(b)

[1 1 1]


Если нужно создать массив, заполненный нулями, длины другого массива, то можно использовать конструкцию

In [12]:
np.zeros_like(b)

array([0, 0, 0], dtype=int64)

Функция `arange` подобна `range`. Аргументы могут быть с плавающей точкой. Следует избегать ситуаций, когда $(конец-начало)/шаг$ - целое число, потому что в этом случае включение последнего элемента зависит от ошибок округления. Лучше, чтобы конец диапазона был где-то посредине шага.

In [13]:
a = np.arange(0, 9, 2)
print(a)

[0 2 4 6 8]


In [14]:
b = np.arange(0., 9, 2)
print(b)

[0. 2. 4. 6. 8.]


Последовательности чисел с постоянным шагом можно также создавать функцией `linspace`. Начало и конец диапазона включаются; последний аргумент - число точек.

In [ ]:
a = np.linspace(0, 8, 5)
print(a)

In [ ]:
a = np.linspace(0, 0.1, 5)
print(a)

Массив случайных чисел (из непрерывного равномерного распределения).

In [ ]:
print(np.random.random(5))

Случайные числа с нормальным (гауссовым) распределением (среднее `0`, среднеквадратичное отклонение `1`).

In [ ]:
print(np.random.normal(size=5))

## Операции над одномерными массивами

Арифметические операции проводятся поэлементно.

In [ ]:
print(a + b)

In [ ]:
print(a - b)

In [ ]:
print(a * b)

In [ ]:
print(a / (b + 1))

In [ ]:
print(a ** 2)

Когда операнды разных типов, они пpиводятся к большему типу.

In [ ]:
i = np.ones(5, dtype=np.int64)
print(a + i)

`numpy` содержит элементарные функции, которые тоже применяются к массивам поэлементно. Они называются универсальными функциями (`ufunc`).

In [ ]:
np.sin, type(np.sin)

In [ ]:
print(np.sin(a))
print(np.cosh(a))

Один из операндов может быть скаляром, а не массивом.

In [ ]:
print(a + 1)

In [ ]:
print(2 * a)

Сравнения дают булевы массивы.

In [ ]:
print(a > b)

In [ ]:
print(a == b)

In [ ]:
c = a > 5
print(c)

Кванторы "существует" и "для всех".

In [ ]:
np.any(c), np.all(c)

Модификация на месте.

In [ ]:
a += 1
print(a)

In [ ]:
b *= 2
print(b)

In [ ]:
b /= a
print(b)

При выполнении операций над массивами деление на 0 не возбуждает исключения, а даёт значения `np.nan` или `np.inf`.

In [ ]:
np.nan + 1, np.inf + 1, np.inf * 0, 1. / np.inf

Сумма и произведение всех элементов массива; максимальный и минимальный элемент; среднее и среднеквадратичное отклонение.

In [ ]:
b.sum(), b.prod(), b.max(), b.min(), b.mean(), b.std()

In [ ]:
x = np.random.normal(size=1000)
x.mean(), x.std()

Имеются встроенные функции

In [ ]:
print(np.sqrt(b))
print(np.exp(b))
print(np.log(b + 1))
print(np.sin(b))
print(np.e, np.pi)

Иногда бывает нужно использовать частичные (кумулятивные) суммы. В нашем курсе такое пригодится.

In [ ]:
print(b.cumsum()[::-1])

Функция `sort` возвращает отсортированную копию, метод `sort` сортирует на месте.

In [ ]:
np.random.shuffle(b)
print(np.sort(b))
print(b)

In [ ]:
b.sort()
print(b)

Объединение массивов "по-горизонтали" (horizontal stack).

In [ ]:
a = np.array([1, 2, 3])
b = np.array([100, 200, 300])

print(np.hstack((a, b)))

Объединение массивов "по-вертикали" (vertical stack).

In [ ]:
print(np.vstack((a, b)))

Расщепление массива в позициях 3 и 6.

In [ ]:
a = np.random.random(10)
np.hsplit(a, [3, 6])

Функции `delete`, `insert` и `append` не меняют массив на месте, а возвращают новый массив, в котором удалены, вставлены в середину или добавлены в конец какие-то элементы.

In [ ]:
a = np.arange(10)

In [ ]:
a = np.delete(a, [5, 7])
print(a)

In [ ]:
a = np.insert(a, 2, [0, 0])
print(a)

In [ ]:
a = np.append(a, [1, 2, 3])
print(a)

Есть несколько способов индексации массива. Вот обычный индекс.

In [ ]:
a = np.linspace(0, 1, 11)
print(a)

In [ ]:
b = a[2]
print(b)

Диапазон индексов. Создаётся новый заголовок массива, указывающий на те же данные. Изменения, сделанные через такой массив, видны и в исходном массиве.

In [ ]:
b = a[2:6]
print(b)

In [ ]:
b[0] = -0.2
print(b)

In [ ]:
print(a)

Диапазон с шагом 2.

In [ ]:
b = a[1:10:2]
print(b)

In [ ]:
b[0] = -0.1
print(a)

Массив в обратном порядке.

In [ ]:
b = a[len(a):0:-1]
print(b)

Подмассиву можно присвоить значение - массив правильного размера или скаляр.

In [ ]:
a[1:10:3] = 0
print(a)

Тут опять создаётся только новый заголовок, указывающий на те же данные.

In [ ]:
b = a[:]
b[1] = 0.1
print(a)

Чтобы скопировать и данные массива, нужно использовать метод `copy`.

In [ ]:
b = a.copy()
b[2] = 0
print(b)
print(a)

Можно задать список индексов.

In [ ]:
print(a[[2, 3, 5]])

Можно задать булев массив той же величины.

In [ ]:
b = a > 0
print(b)

In [ ]:
print(a[b])

## 2-мерные массивы

In [ ]:
a = np.array([[0.0, 1.0], [-1.0, 0.0]])
print(a)

In [ ]:
a.ndim

In [ ]:
a.shape

In [ ]:
len(a), a.size

In [ ]:
a[1, 0]

Атрибуту `shape` можно присвоить новое значение - кортеж размеров по всем координатам. Получится новый заголовок массива; его данные не изменятся.

In [3]:
b = np.linspace(0, 3, 4)
print(b)

[0. 1. 2. 3.]


In [4]:
b.shape

(4,)

In [ ]:
b.shape = 2, 2
print(b)

Можно растянуть в одномерный массив

In [ ]:
print(b.ravel())

Арифметические операции поэлементные

In [ ]:
print(a + 1)
print(a * 2)
print(a + [0, 1])  # второе слагаемое дополняется до матрицы копированием строк
print(a + np.array([[0, 2]]).T)  # .T - транспонирование
print(a + b)

Поэлементное и матричное (только в Python 3.5) умножение.

In [ ]:
print(a * b)

In [ ]:
print(a @ b)

In [ ]:
print(b @ a)

Умножение матрицы на вектор.

In [ ]:
v = np.array([1, -1], dtype=np.float64)
print(b @ v)

In [ ]:
print(v @ b)

Если у вас Питон более ранней версии, то для работы с матрицами можно использовать класс `np.matrix`, в котором операция умножения реализуется как матричное умножение.

In [ ]:
np.matrix(a) * np.matrix(b)

Внешнее произведение $a_{ij}=u_i v_j$

In [ ]:
u = np.linspace(1, 2, 2)
v = np.linspace(2, 4, 3)
print(u)
print(v)

In [ ]:
a = np.outer(u, v)
print(a)

Двумерные массивы, зависящие только от одного индекса: $x_{ij}=u_j$, $y_{ij}=v_i$

In [ ]:
x, y = np.meshgrid(u, v)
print(x)
print(y)

Единичная матрица.

In [ ]:
I = np.eye(4)
print(I)

Метод `reshape` делает то же самое, что присваивание атрибуту `shape`.

In [ ]:
print(I.reshape(16))

In [ ]:
print(I.reshape(2, 8))

Строка.

In [ ]:
print(I[1])

Цикл по строкам.

In [ ]:
for row in I:
    print(row)

Столбец.

In [ ]:
print(I[:, 2])

Подматрица.

In [ ]:
print(I[0:2, 1:3])

Можно построить двумерный массив из функции.

In [ ]:
def f(i, j):
    print(i)
    print(j)
    return 10 * i + j

print(np.fromfunction(f, (4, 4), dtype=np.int64))

Транспонированная матрица.

In [ ]:
print(b.T)

Соединение матриц по горизонтали и по вертикали.

In [ ]:
a = np.array([[0, 1], [2, 3]])
b = np.array([[4, 5, 6], [7, 8, 9]])
c = np.array([[4, 5], [6, 7], [8, 9]])
print(a)
print(b)
print(c)

In [ ]:
print(np.hstack((a, b)))

In [ ]:
print(np.vstack((a, c)))

Сумма всех элементов; суммы столбцов; суммы строк.

In [ ]:
print(b.sum())
print(b.sum(axis=0))
print(b.sum(axis=1))

Аналогично работают `prod`, `max`, `min` и т.д.

In [ ]:
print(b.max())
print(b.max(axis=0))
print(b.min(axis=1))

След - сумма диагональных элементов.

In [ ]:
np.trace(a)

## Многомерные массивы
опциональный материал

In [ ]:
X = np.arange(24).reshape(2, 3, 4)
print(X)

Суммирование (аналогично остальные операции)

In [ ]:
# суммируем только по нулевой оси, то есть для фиксированных j и k суммируем только элементы с индексами (*, j, k)
print(X.sum(axis=0))
# суммируем сразу по двум осям, то есть для фиксированной i суммируем только элементы с индексами (i, *, *)
print(X.sum(axis=(1, 2)))

## Линейная алгебра

In [ ]:
np.linalg.det(a)

Обратная матрица.

In [ ]:
a1 = np.linalg.inv(a)
print(a1)

In [ ]:
print(a @ a1)
print(a1 @ a)

Решение линейной системы $au=v$.

In [ ]:
v = np.array([0, 1], dtype=np.float64)
print(a1 @ v)

In [ ]:
u = np.linalg.solve(a, v)
print(u)

Проверим.

In [ ]:
print(a @ u - v)

Собственные значения и собственные векторы: $a u_i = \lambda_i u_i$. `l` - одномерный массив собственных значений $\lambda_i$, столбцы матрицы $u$ - собственные векторы $u_i$.

In [ ]:
l, u = np.linalg.eig(a)
print(l)

In [ ]:
print(u)

Проверим.

In [ ]:
for i in range(2):
    print(a @ u[:, i] - l[i] * u[:, i])

Функция `diag` от одномерного массива строит диагональную матрицу; от квадратной матрицы - возвращает одномерный массив её диагональных элементов.

In [ ]:
L = np.diag(l)
print(L)
print(np.diag(L))

Все уравнения $a u_i = \lambda_i u_i$ можно собрать в одно матричное уравнение $a u = u \Lambda$, где $\Lambda$ - диагональная матрица с собственными значениями $\lambda_i$ на диагонали.

In [ ]:
print(a @ u - u @ L)

Поэтому $u^{-1} a u = \Lambda$.

In [ ]:
print(np.linalg.inv(u) @ a @ u)

Найдём теперь левые собственные векторы $v_i a = \lambda_i v_i$ (собственные значения $\lambda_i$ те же самые).

In [ ]:
l, v = np.linalg.eig(a.T)
print(l)
print(v)

Собственные векторы нормированы на 1.

In [ ]:
print(u.T @ u)
print(v.T @ v)

Левые и правые собственные векторы, соответствующие разным собственным значениям, ортогональны, потому что $v_i a u_j = \lambda_i v_i u_j = \lambda_j v_i u_j$.

In [ ]:
print(v.T @ u)

# Интегрирование

In [ ]:
from scipy.integrate import quad, odeint
from scipy.special import erf

In [ ]:
def f(x):
    return np.exp(-x ** 2)

Адаптивное численное интегрирование (может быть до бесконечности). `err` - оценка ошибки.

In [ ]:
res, err = quad(f, 0, np.inf)
print(np.sqrt(np.pi) / 2, res, err)

In [ ]:
res, err =  quad(f, 0, 1)
print(np.sqrt(np.pi) / 2 * erf(1), res, err)

## Сохранение в файл и чтение из файла

In [ ]:
x = np.arange(0, 25, 0.5).reshape((5, 10))

# Сохраняем в файл example.txt данные x в формате с двумя точками после запятой и разделителем ';'
np.savetxt('example.txt', x, fmt='%.2f', delimiter=';')

Получится такой файл

In [ ]:
!cat example.txt